export const ADD_TEACHER = 'ADD_TEACHER';
export const TEACHERS_LOADING = 'TEACHERS_LOADING';
export const TEACHERS_FAILED = 'TEACHERS_FAILED';
export const ADD_TIMERECORD = 'ADD_TIMERECORD';
export const TIMERECORDS_LOADING = 'TIMERECORDS_LOADING';
export const TIMERECORDS_FAILED = 'TIMERECORDS_FAILED';