export const ADD_TEACHER = 'ADD_TEACHER';
export const TEACHERS_LOADING = 'TEACHERS_LOADING';
export const TEACHERS_FAILED = 'TEACHERS_FAILED';
export const ADD_COURSE = 'ADD_COURSE';
export const COURSES_LOADING = 'COURSES_LOADING';
export const COURSES_FAILED = 'COURSES_FAILED';